// Regenerates src/renderer/lib/icons.js from the vendored Font Awesome Free
// SVGs. Run with `node scripts/generate-icons.js` after changing ICONS.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const faDir = path.join(rootDir, 'node_modules', '@fortawesome', 'fontawesome-free');
const outFile = path.join(rootDir, 'src', 'renderer', 'lib', 'icons.js');

// App icon name → FA variant/file. Keep this the single source of truth.
const ICONS = {
	'select': 'solid/arrow-pointer',
	'hand': 'regular/hand',
	'card': 'regular/note-sticky',
	'pencil': 'solid/pencil',
	'eraser': 'solid/eraser',
	'square': 'regular/square',
	'circle': 'regular/circle',
	'diamond': 'solid/diamond',
	'arrow-right': 'solid/arrow-right-long',
	'slash': 'solid/slash',
	'file-plus': 'solid/file-circle-plus',
	'globe': 'solid/globe',
	'minus': 'solid/minus',
	'plus': 'solid/plus',
	'expand': 'solid/expand',
	'thumbtack': 'solid/thumbtack',
	'folder-plus': 'solid/folder-plus',
	'chevron-right': 'solid/chevron-right',
	'chevron-left': 'solid/chevron-left',
	'calendar': 'solid/calendar-days',
	'chevron-down': 'solid/chevron-down',
	'xmark': 'solid/xmark',
	'font': 'solid/font',
	'map': 'solid/map-location-dot',
};

const version = JSON.parse(fs.readFileSync(path.join(faDir, 'package.json'), 'utf8')).version;
const entries = [];
for (const [name, file] of Object.entries(ICONS)) {
	const svg = fs.readFileSync(path.join(faDir, 'svgs', `${file}.svg`), 'utf8');
	const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
	const d = /<path[^>]*\bd="([^"]+)"/.exec(svg)?.[1];
	if (!viewBox || !d) throw new Error(`Could not parse ${file}.svg`);
	entries.push(`\t'${name}': { viewBox: '${viewBox}', d: '${d}' },`);
}

fs.writeFileSync(outFile, `// GENERATED by scripts/generate-icons.js — do not edit by hand.
// Icon path data from Font Awesome Free ${version} (fontawesome.com),
// licensed CC BY 4.0 — https://fontawesome.com/license/free
const ICON_PATHS = {
${entries.join('\n')}
};

const SVG_NS = 'http://www.w3.org/2000/svg';

/** An inline SVG icon element (1em square, currentColor). */
export function icon(name, className = '') {
	const spec = ICON_PATHS[name];
	if (!spec) throw new Error(\`Unknown icon: \${name}\`);
	const svg = document.createElementNS(SVG_NS, 'svg');
	svg.setAttribute('viewBox', spec.viewBox);
	svg.setAttribute('class', className ? \`ui-icon \${className}\` : 'ui-icon');
	svg.setAttribute('aria-hidden', 'true');
	const path = document.createElementNS(SVG_NS, 'path');
	path.setAttribute('d', spec.d);
	svg.append(path);
	return svg;
}
`);
console.log(`Wrote ${outFile} (${entries.length} icons, FA ${version})`);
