// Clew — an Obsidian-style note app built on the jmarkdown engine.
// Copyright © 2026 J. McKenzie Alexander <jmckalex@gmail.com> · https://jmckalex.org
//
// This file is part of Clew, free software released under the GNU General
// Public License, version 3 or later. Clew is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY. See LICENSE at the repository
// root, or <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Regenerates src/renderer/lib/icons.js from the vendored Font Awesome Free
// SVGs. Run with `node scripts/generate-icons.js` after changing ICONS.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const faDir = path.join(rootDir, 'node_modules', '@fortawesome', 'fontawesome-free');
const outFile = path.join(rootDir, 'src', 'renderer', 'lib', 'icons.js');

// App icon name → FA variant/file. Keep this the single source of truth.
const ICONS = {
	'select': 'solid/arrow-pointer',
	'hand': 'regular/hand',
	'card': 'regular/note-sticky',
	'pencil': 'solid/pencil',
	'eraser': 'solid/eraser',
	'trash': 'regular/trash-can',
	'square': 'regular/square',
	'circle': 'regular/circle',
	'diamond': 'solid/diamond',
	'arrow-right': 'solid/arrow-right-long',
	'slash': 'solid/slash',
	'file-plus': 'solid/file-circle-plus',
	'globe': 'solid/globe',
	'minus': 'solid/minus',
	'plus': 'solid/plus',
	'expand': 'solid/expand',
	'thumbtack': 'solid/thumbtack',
	'folder-plus': 'solid/folder-plus',
	'chevron-right': 'solid/chevron-right',
	'chevron-left': 'solid/chevron-left',
	'calendar': 'solid/calendar-days',
	'chevron-down': 'solid/chevron-down',
	'xmark': 'solid/xmark',
	'font': 'solid/font',
	'map': 'solid/map-location-dot',
	// Live edit's editor toolbar (docs/dev/live-edit-plan.md §6).
	'bold': 'solid/bold',
	'italic': 'solid/italic',
	'underline': 'solid/underline',
	'highlighter': 'solid/highlighter',
	'strikethrough': 'solid/strikethrough',
	'subscript': 'solid/subscript',
	'superscript': 'solid/superscript',
	'code': 'solid/code',
	'sigma': 'solid/square-root-variable',
	'list-ul': 'solid/list-ul',
	'list-ol': 'solid/list-ol',
	'list-check': 'solid/list-check',
	'outdent': 'solid/outdent',
	'indent': 'solid/indent',
	'link': 'solid/link',
	'image': 'solid/image',
	'table': 'solid/table',
	'callout': 'solid/circle-exclamation',
	'fence': 'solid/file-code',
	'diagram': 'solid/diagram-project',
	'box': 'solid/cube',
	'undo': 'solid/rotate-left',
	'redo': 'solid/rotate-right',
	'heading': 'solid/heading',
	'ellipsis': 'solid/ellipsis',
	'book': 'solid/book-open',
	'wikilink': 'solid/file-lines',
	'intense': 'solid/text-height',
	'row-below': 'solid/arrow-down-short-wide',
	'format': 'solid/align-left',
	// In-place table editing (docs/dev/live-edit.md §5.5c).
	'row-above': 'solid/arrow-up-long',
	'row-delete': 'solid/delete-left',
	'col-left': 'solid/arrow-left-long',
	'col-right': 'solid/arrow-right-long',
	'col-delete': 'solid/square-minus',
	'align-left': 'solid/align-left',
	'align-center': 'solid/align-center',
	'align-right': 'solid/align-right',
};

const version = JSON.parse(fs.readFileSync(path.join(faDir, 'package.json'), 'utf8')).version;
const entries = [];
for (const [name, file] of Object.entries(ICONS)) {
	const svg = fs.readFileSync(path.join(faDir, 'svgs', `${file}.svg`), 'utf8');
	const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
	const d = /<path[^>]*\bd="([^"]+)"/.exec(svg)?.[1];
	if (!viewBox || !d) throw new Error(`Could not parse ${file}.svg`);
	entries.push(`\t'${name}': { viewBox: '${viewBox}', d: '${d}' },`);
}

// The repository's licence header, carried into the output (it had been
// added to icons.js by hand, and regenerating dropped it).
const HEADER = fs.readFileSync(fileURLToPath(import.meta.url), 'utf8').split('\n').slice(0, 10).join('\n');

fs.writeFileSync(outFile, `${HEADER}
// GENERATED by scripts/generate-icons.js — do not edit by hand.
// Icon path data from Font Awesome Free ${version} (fontawesome.com),
// licensed CC BY 4.0 — https://fontawesome.com/license/free
const ICON_PATHS = {
${entries.join('\n')}
};

const SVG_NS = 'http://www.w3.org/2000/svg';

/** An inline SVG icon element (1em square, currentColor). */
export function icon(name, className = '') {
	const spec = ICON_PATHS[name];
	if (!spec) throw new Error(\`Unknown icon: \${name}\`);
	const svg = document.createElementNS(SVG_NS, 'svg');
	svg.setAttribute('viewBox', spec.viewBox);
	svg.setAttribute('class', className ? \`ui-icon \${className}\` : 'ui-icon');
	svg.setAttribute('aria-hidden', 'true');
	const path = document.createElementNS(SVG_NS, 'path');
	path.setAttribute('d', spec.d);
	svg.append(path);
	return svg;
}
`);
console.log(`Wrote ${outFile} (${entries.length} icons, FA ${version})`);
